//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.UI.Localization.AboutDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutDialogR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutDialogR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBFSManager.UI.Localization.AboutDialog.AboutDialogR", typeof(AboutDialogR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitleText {
            get {
                return ResourceManager.GetString("AboutTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional icons and imagery by: BarbaxX.
        /// </summary>
        internal static string AdditionalImagesText {
            get {
                return ResourceManager.GetString("AdditionalImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2009 AlexDP.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap donatePayPal {
            get {
                object obj = ResourceManager.GetObject("donatePayPal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted by:.
        /// </summary>
        internal static string HostedByText {
            get {
                return ResourceManager.GetString("HostedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libwbfs written by: Kwiirk.
        /// </summary>
        internal static string LibWbfsText {
            get {
                return ResourceManager.GetString("LibWbfsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal donations would be greatly appreciated..
        /// </summary>
        internal static string PayPalText {
            get {
                return ResourceManager.GetString("PayPalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename code for libwbfs written by: Sorg.
        /// </summary>
        internal static string RenameByText {
            get {
                return ResourceManager.GetString("RenameByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For use with USB Loader 1.x by Waninkoko.
        /// </summary>
        internal static string USBLoaderText {
            get {
                return ResourceManager.GetString("USBLoaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written By: AlexDP.
        /// </summary>
        internal static string WrittenByText {
            get {
                return ResourceManager.GetString("WrittenByText", resourceCulture);
            }
        }
    }
}
