//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.UI.Localization.OptionsDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptionsDialogR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsDialogR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBFSManager.UI.Localization.OptionsDialog.OptionsDialogR", typeof(OptionsDialogR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedSettingsText {
            get {
                return ResourceManager.GetString("AdvancedSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Check for Updates:.
        /// </summary>
        internal static string AutomaticallyCheckForUpdatesText {
            get {
                return ResourceManager.GetString("AutomaticallyCheckForUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string BasicSettingsText {
            get {
                return ResourceManager.GetString("BasicSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Loader Preset:.
        /// </summary>
        internal static string BootloaderPresetText {
            get {
                return ResourceManager.GetString("BootloaderPresetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Creation.
        /// </summary>
        internal static string ChannelCreationSettingsText {
            get {
                return ResourceManager.GetString("ChannelCreationSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Directories:.
        /// </summary>
        internal static string CoverDirsText {
            get {
                return ResourceManager.GetString("CoverDirsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Covers from Web:.
        /// </summary>
        internal static string DownloadCoversFromWebText {
            get {
                return ResourceManager.GetString("DownloadCoversFromWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Channel Creation.
        /// </summary>
        internal static string EnableChannelCreationText {
            get {
                return ResourceManager.GetString("EnableChannelCreationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatic RAR Extraction:.
        /// </summary>
        internal static string EnableRarExtractionText {
            get {
                return ResourceManager.GetString("EnableRarExtractionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Settings.
        /// </summary>
        internal static string InitialSettingsText {
            get {
                return ResourceManager.GetString("InitialSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Key File:.
        /// </summary>
        internal static string KeyFileText {
            get {
                return ResourceManager.GetString("KeyFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Loader DOL File:.
        /// </summary>
        internal static string LoaderFileText {
            get {
                return ResourceManager.GetString("LoaderFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID Placeholder:.
        /// </summary>
        internal static string OriginalTitleIDText {
            get {
                return ResourceManager.GetString("OriginalTitleIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions to keep:.
        /// </summary>
        internal static string PartitionsToKeepText {
            get {
                return ResourceManager.GetString("PartitionsToKeepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Covers:.
        /// </summary>
        internal static string ShowCoversText {
            get {
                return ResourceManager.GetString("ShowCoversText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base WAD File:.
        /// </summary>
        internal static string SrcWadFileText {
            get {
                return ResourceManager.GetString("SrcWadFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Folder:.
        /// </summary>
        internal static string TempFolderText {
            get {
                return ResourceManager.GetString("TempFolderText", resourceCulture);
            }
        }
    }
}
