//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.UI.Localization.WelcomeDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WelcomeDialogR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WelcomeDialogR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBFSManager.UI.Localization.WelcomeDialog.WelcomeDialogR", typeof(WelcomeDialogR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. If you haven&apos;t already formatted your hard drive or usb drive to the WBFS format, select the drive letter from the menu at the top left and click the Format button. If you&apos;ve already formatted, click the Load button..
        /// </summary>
        internal static string Instructions1Text {
            get {
                return ResourceManager.GetString("Instructions1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Once your hard drive is loaded you will see a list of games on the WBFS drive on the left side..
        /// </summary>
        internal static string Instructions2Text {
            get {
                return ResourceManager.GetString("Instructions2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -To add games To the WBFS drive, click the Browse button and select the game iso, or drag and drop the game onto the list on the right-hand side from Windows Explorer. Then click the Add To Drive button..
        /// </summary>
        internal static string InstructionsAddText {
            get {
                return ResourceManager.GetString("InstructionsAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This welcome screen will not appear in the future..
        /// </summary>
        internal static string InstructionsEndText {
            get {
                return ResourceManager.GetString("InstructionsEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -To extract games from the WBFS drive, select a game from the list on the left and click extract..
        /// </summary>
        internal static string InstructionsExtrText {
            get {
                return ResourceManager.GetString("InstructionsExtrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:.
        /// </summary>
        internal static string InstructionsText {
            get {
                return ResourceManager.GetString("InstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WBFS Manager 3.0.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
