//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.UI.Localization.MainWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBFSManager.UI.Localization.MainWindow.MainWindowR", typeof(MainWindowR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        internal static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Dr_ive.
        /// </summary>
        internal static string AddToDriveButtonText {
            get {
                return ResourceManager.GetString("AddToDriveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add to Drive.
        /// </summary>
        internal static string AddToDriveMenuText {
            get {
                return ResourceManager.GetString("AddToDriveMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks Free:.
        /// </summary>
        internal static string BlocksUsedText {
            get {
                return ResourceManager.GetString("BlocksUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse....
        /// </summary>
        internal static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckForUpdatesMenuText {
            get {
                return ResourceManager.GetString("CheckForUpdatesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear.
        /// </summary>
        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string CloneText {
            get {
                return ResourceManager.GetString("CloneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Channel(s).
        /// </summary>
        internal static string CreateChannelsText {
            get {
                return ResourceManager.GetString("CreateChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        internal static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Game.
        /// </summary>
        internal static string DeleteGameText {
            get {
                return ResourceManager.GetString("DeleteGameText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap donatePayPalSmall {
            get {
                object obj = ResourceManager.GetObject("donatePayPalSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Covers from Web.
        /// </summary>
        internal static string DownloadCoversFromWebText {
            get {
                return ResourceManager.GetString("DownloadCoversFromWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive:.
        /// </summary>
        internal static string DriveLabelText {
            get {
                return ResourceManager.GetString("DriveLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to this Drive.
        /// </summary>
        internal static string DriveToDriveCopyText {
            get {
                return ResourceManager.GetString("DriveToDriveCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive-To-Drive.
        /// </summary>
        internal static string DriveToDriveText {
            get {
                return ResourceManager.GetString("DriveToDriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string EditLanguageMenuText {
            get {
                return ResourceManager.GetString("EditLanguageMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set Covers Directory....
        /// </summary>
        internal static string EditSetCoverDirText {
            get {
                return ResourceManager.GetString("EditSetCoverDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Covers.
        /// </summary>
        internal static string EditShowCoversText {
            get {
                return ResourceManager.GetString("EditShowCoversText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string EditShowOptionsText {
            get {
                return ResourceManager.GetString("EditShowOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Total Size:.
        /// </summary>
        internal static string EstimatedTotalSizeText {
            get {
                return ResourceManager.GetString("EstimatedTotalSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string ExitMenuText {
            get {
                return ResourceManager.GetString("ExitMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export List to File.
        /// </summary>
        internal static string ExportListToFileText {
            get {
                return ResourceManager.GetString("ExportListToFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extract ISO....
        /// </summary>
        internal static string ExtractMenuText {
            get {
                return ResourceManager.GetString("ExtractMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string FormatText {
            get {
                return ResourceManager.GetString("FormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space:.
        /// </summary>
        internal static string FreeSpaceText {
            get {
                return ResourceManager.GetString("FreeSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games on WBFS Drive:.
        /// </summary>
        internal static string GamesOnDriveLabelText {
            get {
                return ResourceManager.GetString("GamesOnDriveLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games on Secondary WBFS Drive:.
        /// </summary>
        internal static string GamesOnSecondaryText {
            get {
                return ResourceManager.GetString("GamesOnSecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games to add to WBFS Drive:.
        /// </summary>
        internal static string GamesToAddLabelText {
            get {
                return ResourceManager.GetString("GamesToAddLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items:.
        /// </summary>
        internal static string ItemsText {
            get {
                return ResourceManager.GetString("ItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Cover View.
        /// </summary>
        internal static string LargeCoverViewText {
            get {
                return ResourceManager.GetString("LargeCoverViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load.
        /// </summary>
        internal static string LoadText {
            get {
                return ResourceManager.GetString("LoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make HBC _Entries for All.
        /// </summary>
        internal static string MakeAllHBCMenuText {
            get {
                return ResourceManager.GetString("MakeAllHBCMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make HBC Entry.
        /// </summary>
        internal static string MakeSingleHBCMenuText {
            get {
                return ResourceManager.GetString("MakeSingleHBCMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        internal static string OnlineHelpMenuText {
            get {
                return ResourceManager.GetString("OnlineHelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Drive List.
        /// </summary>
        internal static string RefreshDriveListText {
            get {
                return ResourceManager.GetString("RefreshDriveListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove From List.
        /// </summary>
        internal static string RemoveFromListText {
            get {
                return ResourceManager.GetString("RemoveFromListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameButtonText {
            get {
                return ResourceManager.GetString("RenameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        internal static string RenameMenuText {
            get {
                return ResourceManager.GetString("RenameMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items:.
        /// </summary>
        internal static string SelectedItemsText {
            get {
                return ResourceManager.GetString("SelectedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string SortByIdMenuText {
            get {
                return ResourceManager.GetString("SortByIdMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Location.
        /// </summary>
        internal static string SortByIsoLocMenuText {
            get {
                return ResourceManager.GetString("SortByIsoLocMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location on Drive.
        /// </summary>
        internal static string SortByLocationMenuText {
            get {
                return ResourceManager.GetString("SortByLocationMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortByMenuText {
            get {
                return ResourceManager.GetString("SortByMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortByNameMenuText {
            get {
                return ResourceManager.GetString("SortByNameMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SortBySizeMenuText {
            get {
                return ResourceManager.GetString("SortBySizeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SortByStatusMenuText {
            get {
                return ResourceManager.GetString("SortByStatusMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Space:.
        /// </summary>
        internal static string TotalSpaceText {
            get {
                return ResourceManager.GetString("TotalSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        internal static string UnloadText {
            get {
                return ResourceManager.GetString("UnloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Space:.
        /// </summary>
        internal static string UsedSpaceText {
            get {
                return ResourceManager.GetString("UsedSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Blog.
        /// </summary>
        internal static string VisitBlogMenuText {
            get {
                return ResourceManager.GetString("VisitBlogMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Download Site.
        /// </summary>
        internal static string VisitDownloadMenuText {
            get {
                return ResourceManager.GetString("VisitDownloadMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WBFS Drive.
        /// </summary>
        internal static string WBFSDriveMenuText {
            get {
                return ResourceManager.GetString("WBFSDriveMenuText", resourceCulture);
            }
        }
    }
}
