//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBFSManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel creation completed..
        /// </summary>
        internal static string ChannCreationCompleteStr {
            get {
                return ResourceManager.GetString("ChannCreationCompleteStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a temporary folder:.
        /// </summary>
        internal static string ChooseTempFolderText {
            get {
                return ResourceManager.GetString("ChooseTempFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Adding..
        /// </summary>
        internal static string CompletedAddingShortStr {
            get {
                return ResourceManager.GetString("CompletedAddingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed adding entries to WBFS drive..
        /// </summary>
        internal static string CompletedAddingStr {
            get {
                return ResourceManager.GetString("CompletedAddingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel creation successful.
        /// </summary>
        internal static string CompletedChanCreationSuccessShortStr {
            get {
                return ResourceManager.GetString("CompletedChanCreationSuccessShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel creation completed successfully.
        /// </summary>
        internal static string CompletedChannelCreationSuccessStr {
            get {
                return ResourceManager.GetString("CompletedChannelCreationSuccessStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed exporting list to file..
        /// </summary>
        internal static string CompletedExportingListStr {
            get {
                return ResourceManager.GetString("CompletedExportingListStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction completed..
        /// </summary>
        internal static string CompletedExtractShortStr {
            get {
                return ResourceManager.GetString("CompletedExtractShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed extraction from WBFS drive..
        /// </summary>
        internal static string CompletedExtractStr {
            get {
                return ResourceManager.GetString("CompletedExtractStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Hombrew Channel entry creation..
        /// </summary>
        internal static string CompletedHBCEntryStr {
            get {
                return ResourceManager.GetString("CompletedHBCEntryStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CompletedStr {
            get {
                return ResourceManager.GetString("CompletedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove?.
        /// </summary>
        internal static string ConfirmDeleteShortStr {
            get {
                return ResourceManager.GetString("ConfirmDeleteShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove .
        /// </summary>
        internal static string ConfirmDeleteStr {
            get {
                return ResourceManager.GetString("ConfirmDeleteStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Progress.
        /// </summary>
        internal static string CopyProgressStr {
            get {
                return ResourceManager.GetString("CopyProgressStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating channels....
        /// </summary>
        internal static string CreatingChannelsProgressText {
            get {
                return ResourceManager.GetString("CreatingChannelsProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Covers?.
        /// </summary>
        internal static string DownloadFromWebPromptShortText {
            get {
                return ResourceManager.GetString("DownloadFromWebPromptShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enable downloading covers from the web? (You can change this setting later in the Edit menu.).
        /// </summary>
        internal static string DownloadFromWebPromptText {
            get {
                return ResourceManager.GetString("DownloadFromWebPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive-To-Drive Transfer Progress.
        /// </summary>
        internal static string DriveToDriveProgressStr {
            get {
                return ResourceManager.GetString("DriveToDriveProgressStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . The disc already exists on the WBFS drive..
        /// </summary>
        internal static string ErrorAddExistsStr {
            get {
                return ResourceManager.GetString("ErrorAddExistsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding disc..
        /// </summary>
        internal static string ErrorAddingNoDriveShortStr {
            get {
                return ResourceManager.GetString("ErrorAddingNoDriveShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while adding disc to WBFS drive.  Could not access drive..
        /// </summary>
        internal static string ErrorAddingNoDriveStr {
            get {
                return ResourceManager.GetString("ErrorAddingNoDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading Files.
        /// </summary>
        internal static string ErrorAddingShortStr {
            get {
                return ResourceManager.GetString("ErrorAddingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while adding files to Games to Add list. Try selecting less folders..
        /// </summary>
        internal static string ErrorAddingStr {
            get {
                return ResourceManager.GetString("ErrorAddingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . An error occurred while loading the WBFS drive..
        /// </summary>
        internal static string ErrorAddLoadingStr {
            get {
                return ResourceManager.GetString("ErrorAddLoadingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . An error occurred while attempting to read the image file from disk..
        /// </summary>
        internal static string ErrorAddReadStr {
            get {
                return ResourceManager.GetString("ErrorAddReadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID must be exactly 4 characters..
        /// </summary>
        internal static string ErrorChanIdMustBeFourStr {
            get {
                return ResourceManager.GetString("ErrorChanIdMustBeFourStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Error code .
        /// </summary>
        internal static string ErrorCodeStr {
            get {
                return ResourceManager.GetString("ErrorCodeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating channel.
        /// </summary>
        internal static string ErrorCreatinChanSingleStr {
            get {
                return ResourceManager.GetString("ErrorCreatinChanSingleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while creating channel for .
        /// </summary>
        internal static string ErrorCreatingChanForStr {
            get {
                return ResourceManager.GetString("ErrorCreatingChanForStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while creating channel. (Error code .
        /// </summary>
        internal static string ErrorCreatingChannelErrCodeStr {
            get {
                return ResourceManager.GetString("ErrorCreatingChannelErrCodeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating HBC Entry.
        /// </summary>
        internal static string ErrorCreatingHBCShortStr {
            get {
                return ResourceManager.GetString("ErrorCreatingHBCShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating HBC entry, missing the .dol file..
        /// </summary>
        internal static string ErrorCreatingHBCStr {
            get {
                return ResourceManager.GetString("ErrorCreatingHBCStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game disc could not be found on WBFS drive..
        /// </summary>
        internal static string ErrorDeleteNotFoundStr {
            get {
                return ResourceManager.GetString("ErrorDeleteNotFoundStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing game.
        /// </summary>
        internal static string ErrorDeleteShortStr {
            get {
                return ResourceManager.GetString("ErrorDeleteShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while removing game:.
        /// </summary>
        internal static string ErrorDeleteStr {
            get {
                return ResourceManager.GetString("ErrorDeleteStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty entry list.
        /// </summary>
        internal static string ErrorEmptyEntryListShortStr {
            get {
                return ResourceManager.GetString("ErrorEmptyEntryListShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of entries to create channels for is empty..
        /// </summary>
        internal static string ErrorEmptyEntryListStr {
            get {
                return ResourceManager.GetString("ErrorEmptyEntryListStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the WBFS drive..
        /// </summary>
        internal static string ErrorEstimateLoadingDriveStr {
            get {
                return ResourceManager.GetString("ErrorEstimateLoadingDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to read the image file from disk..
        /// </summary>
        internal static string ErrorEstimateReadingImageStr {
            get {
                return ResourceManager.GetString("ErrorEstimateReadingImageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error estimating game size..
        /// </summary>
        internal static string ErrorEstimatingShortStr {
            get {
                return ResourceManager.GetString("ErrorEstimatingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error estimating:.
        /// </summary>
        internal static string ErrorEstimatingStr {
            get {
                return ResourceManager.GetString("ErrorEstimatingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries exist..
        /// </summary>
        internal static string ErrorExtractingNoEntriesShortStr {
            get {
                return ResourceManager.GetString("ErrorExtractingNoEntriesShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries exist on drive to extract iso from..
        /// </summary>
        internal static string ErrorExtractingNoEntriesStr {
            get {
                return ResourceManager.GetString("ErrorExtractingNoEntriesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting game..
        /// </summary>
        internal static string ErrorExtractingP1ShortStr {
            get {
                return ResourceManager.GetString("ErrorExtractingP1ShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while extracting.
        /// </summary>
        internal static string ErrorExtractingP1Str {
            get {
                return ResourceManager.GetString("ErrorExtractingP1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting RAR.
        /// </summary>
        internal static string ErrorExtractingRARShortStr {
            get {
                return ResourceManager.GetString("ErrorExtractingRARShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting disc..
        /// </summary>
        internal static string ErrorExtractingShortStr {
            get {
                return ResourceManager.GetString("ErrorExtractingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while extracting disc from drive.  Could not access drive..
        /// </summary>
        internal static string ErrorExtractingStr {
            get {
                return ResourceManager.GetString("ErrorExtractingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . An error occurred while loading the WBFS drive..
        /// </summary>
        internal static string ErrorExtrLoadingStr {
            get {
                return ResourceManager.GetString("ErrorExtrLoadingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Unable to open file on WBFS drive for writing..
        /// </summary>
        internal static string ErrorExtrNoDriveStr {
            get {
                return ResourceManager.GetString("ErrorExtrNoDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . The game disc could not be found on the WBFS drive..
        /// </summary>
        internal static string ErrorExtrNoGameStr {
            get {
                return ResourceManager.GetString("ErrorExtrNoGameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred while transferring: .
        /// </summary>
        internal static string ErrorFollowingWhileTransStr {
            get {
                return ResourceManager.GetString("ErrorFollowingWhileTransStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to close the drive..
        /// </summary>
        internal static string ErrorFormatClosingDriveStr {
            get {
                return ResourceManager.GetString("ErrorFormatClosingDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Drive Letter..
        /// </summary>
        internal static string ErrorFormatInvalidShortStr {
            get {
                return ResourceManager.GetString("ErrorFormatInvalidShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid drive letter selected for formatting..
        /// </summary>
        internal static string ErrorFormatInvalidStr {
            get {
                return ResourceManager.GetString("ErrorFormatInvalidStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error formatting.
        /// </summary>
        internal static string ErrorFormatShortStr {
            get {
                return ResourceManager.GetString("ErrorFormatShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to format the drive..
        /// </summary>
        internal static string ErrorFormatStr {
            get {
                return ResourceManager.GetString("ErrorFormatStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect version.
        /// </summary>
        internal static string ErrorIncorrectVersionShortStr {
            get {
                return ResourceManager.GetString("ErrorIncorrectVersionShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of WBFS Manager is not compatible with your operating system. If you are using a 64-bit operating system, please install the 64-bit version of WBFS Manager (x64)..
        /// </summary>
        internal static string ErrorIncorrectVersionStr {
            get {
                return ResourceManager.GetString("ErrorIncorrectVersionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base WAD filename, file does not exist..
        /// </summary>
        internal static string ErrorInvalidBaseWadFilenameStr {
            get {
                return ResourceManager.GetString("ErrorInvalidBaseWadFilenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values for channel creation settings..
        /// </summary>
        internal static string ErrorInvalidChanCreationValsStr {
            get {
                return ResourceManager.GetString("ErrorInvalidChanCreationValsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel ID or output filename..
        /// </summary>
        internal static string ErrorInvalidChanIdOrOutFileStr {
            get {
                return ResourceManager.GetString("ErrorInvalidChanIdOrOutFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel ID.
        /// </summary>
        internal static string ErrorInvalidChanIdStr {
            get {
                return ResourceManager.GetString("ErrorInvalidChanIdStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel creation settings. Please fix the settings in the Options menu..
        /// </summary>
        internal static string ErrorInvalidChannelSettingsFixStr {
            get {
                return ResourceManager.GetString("ErrorInvalidChannelSettingsFixStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid common key filename, file does not exist..
        /// </summary>
        internal static string ErrorInvalidCommonKeyFilenameStr {
            get {
                return ResourceManager.GetString("ErrorInvalidCommonKeyFilenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid USB Loader .dol filename, file does not exist..
        /// </summary>
        internal static string ErrorInvalidDolFilenameStr {
            get {
                return ResourceManager.GetString("ErrorInvalidDolFilenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filename.
        /// </summary>
        internal static string ErrorInvalidFilename {
            get {
                return ResourceManager.GetString("ErrorInvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        internal static string ErrorInvalidFolderShortStr {
            get {
                return ResourceManager.GetString("ErrorInvalidFolderShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder selected, select a different folder..
        /// </summary>
        internal static string ErrorInvalidFolderStr {
            get {
                return ResourceManager.GetString("ErrorInvalidFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO file path for .
        /// </summary>
        internal static string ErrorInvalidIsoPathForStr {
            get {
                return ResourceManager.GetString("ErrorInvalidIsoPathForStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO path.
        /// </summary>
        internal static string ErrorInvalidIsoPathShortStr {
            get {
                return ResourceManager.GetString("ErrorInvalidIsoPathShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO file path..
        /// </summary>
        internal static string ErrorInvalidIsoPathStr {
            get {
                return ResourceManager.GetString("ErrorInvalidIsoPathStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output WAD filename..
        /// </summary>
        internal static string ErrorInvalidOuputWadFilenameStr {
            get {
                return ResourceManager.GetString("ErrorInvalidOuputWadFilenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partiiton setting selected..
        /// </summary>
        internal static string ErrorInvalidPartitionSettingStr {
            get {
                return ResourceManager.GetString("ErrorInvalidPartitionSettingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings..
        /// </summary>
        internal static string ErrorInvalidSettingsStr {
            get {
                return ResourceManager.GetString("ErrorInvalidSettingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values.
        /// </summary>
        internal static string ErrorInvalidValsShortStr {
            get {
                return ResourceManager.GetString("ErrorInvalidValsShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading drive.
        /// </summary>
        internal static string ErrorLoadingDriveShortStr {
            get {
                return ResourceManager.GetString("ErrorLoadingDriveShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while loading drive. Make sure the drive is not in use or open and that it has been formatted to WBFS format..
        /// </summary>
        internal static string ErrorLoadingDriveStr {
            get {
                return ResourceManager.GetString("ErrorLoadingDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries exist on source drive..
        /// </summary>
        internal static string ErrorNoEntriesOnSourceDriveStr {
            get {
                return ResourceManager.GetString("ErrorNoEntriesOnSourceDriveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries exist on source drive or none were selected..
        /// </summary>
        internal static string ErrorNoEntriesOnSourceNonSelectedStr {
            get {
                return ResourceManager.GetString("ErrorNoEntriesOnSourceNonSelectedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No secondary drive loaded to copy games to..
        /// </summary>
        internal static string ErrorNoSecondaryDriveLoadedStr {
            get {
                return ResourceManager.GetString("ErrorNoSecondaryDriveLoadedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , not enough space..
        /// </summary>
        internal static string ErrorNotEnoughSpaceLowerStr {
            get {
                return ResourceManager.GetString("ErrorNotEnoughSpaceLowerStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Space.
        /// </summary>
        internal static string ErrorNotEnoughSpaceShortStr {
            get {
                return ResourceManager.GetString("ErrorNotEnoughSpaceShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space in temporary folder, choose a different temporary folder with at least 4.8 GB free..
        /// </summary>
        internal static string ErrorNotEnoughSpaceTempFolderStr {
            get {
                return ResourceManager.GetString("ErrorNotEnoughSpaceTempFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space on secondary drive to clone the source drive..
        /// </summary>
        internal static string ErrorNotEnoughSpaceToCloneStr {
            get {
                return ResourceManager.GetString("ErrorNotEnoughSpaceToCloneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while extracting some games. Hover your mouse over the error icon next to each game to read the error..
        /// </summary>
        internal static string ErrorOccuredExtractingStr {
            get {
                return ResourceManager.GetString("ErrorOccuredExtractingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Transferring.
        /// </summary>
        internal static string ErrorOccuredWhileTransShortStr {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileTransShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while transferring: .
        /// </summary>
        internal static string ErrorOccuredWhileTransStr {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileTransStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing volume: .
        /// </summary>
        internal static string ErrorRARMissingVolP1Str {
            get {
                return ResourceManager.GetString("ErrorRARMissingVolP1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from RAR set for file: .
        /// </summary>
        internal static string ErrorRarMissingVolP2Str {
            get {
                return ResourceManager.GetString("ErrorRarMissingVolP2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Volume.
        /// </summary>
        internal static string ErrorRarMissingVolShortStr {
            get {
                return ResourceManager.GetString("ErrorRarMissingVolShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        internal static string ErrorRarPassReqdShortStr {
            get {
                return ResourceManager.GetString("ErrorRarPassReqdShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required for: .
        /// </summary>
        internal static string ErrorRarPassReqdStr {
            get {
                return ResourceManager.GetString("ErrorRarPassReqdStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading drive statistics..
        /// </summary>
        internal static string ErrorReadingDriveStatsShortStr {
            get {
                return ResourceManager.GetString("ErrorReadingDriveStatsShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading drive statistics. Could not access drive..
        /// </summary>
        internal static string ErrorReadingDriveStatsStr {
            get {
                return ResourceManager.GetString("ErrorReadingDriveStatsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading ISO info..
        /// </summary>
        internal static string ErrorReadingISOShortStr {
            get {
                return ResourceManager.GetString("ErrorReadingISOShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading ISO info.  Could not access drive..
        /// </summary>
        internal static string ErrorReadingISOStr {
            get {
                return ResourceManager.GetString("ErrorReadingISOStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occurred while reading some of the ISO files..
        /// </summary>
        internal static string ErrorReadingSomeIsosStr {
            get {
                return ResourceManager.GetString("ErrorReadingSomeIsosStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load game..
        /// </summary>
        internal static string ErrorRenameCantLoadStr {
            get {
                return ResourceManager.GetString("ErrorRenameCantLoadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name..
        /// </summary>
        internal static string ErrorRenameInvalidShortStr {
            get {
                return ResourceManager.GetString("ErrorRenameInvalidShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name specified. Name must be between 0 and 57 characters long..
        /// </summary>
        internal static string ErrorRenameInvalidStr {
            get {
                return ResourceManager.GetString("ErrorRenameInvalidStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Renaming Disc.
        /// </summary>
        internal static string ErrorRenameShortStr {
            get {
                return ResourceManager.GetString("ErrorRenameShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while renaming the disc..
        /// </summary>
        internal static string ErrorRenameStr {
            get {
                return ResourceManager.GetString("ErrorRenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred creating channels.
        /// </summary>
        internal static string ErrorsCreatingChannelsStr {
            get {
                return ResourceManager.GetString("ErrorsCreatingChannelsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while extracting..
        /// </summary>
        internal static string ErrorsOccuredExtractingShortStr {
            get {
                return ResourceManager.GetString("ErrorsOccuredExtractingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while adding..
        /// </summary>
        internal static string ErrorsOccuredWhileAddingShortStr {
            get {
                return ResourceManager.GetString("ErrorsOccuredWhileAddingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while adding some games. Hover your mouse over the error icon next to each game to read the error..
        /// </summary>
        internal static string ErrorsOccuredWhileAddingStr {
            get {
                return ResourceManager.GetString("ErrorsOccuredWhileAddingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Transferring.
        /// </summary>
        internal static string ErrorsTransShortStr {
            get {
                return ResourceManager.GetString("ErrorsTransShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create directory.
        /// </summary>
        internal static string ErrorUnableToCreateDirShortStr {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateDirShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create temp directory: .
        /// </summary>
        internal static string ErrorUnableToCreateTempDirStr {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateTempDirStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding game..
        /// </summary>
        internal static string ErrorWhileAddingShortStr {
            get {
                return ResourceManager.GetString("ErrorWhileAddingShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while adding:.
        /// </summary>
        internal static string ErrorWhileAddingStr {
            get {
                return ResourceManager.GetString("ErrorWhileAddingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Progress.
        /// </summary>
        internal static string ExtractionProgressStr {
            get {
                return ResourceManager.GetString("ExtractionProgressStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Successful.
        /// </summary>
        internal static string FormatSuccessfulShortStr {
            get {
                return ResourceManager.GetString("FormatSuccessfulShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format completed successfully. The WBFS drive is now ready..
        /// </summary>
        internal static string FormatSuccessfulStr {
            get {
                return ResourceManager.GetString("FormatSuccessfulStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This will delete all data on the selected partition (.
        /// </summary>
        internal static string FormatWarningP1Str {
            get {
                return ResourceManager.GetString("FormatWarningP1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ). Data will not be recoverable. The developer will not be held responsible for any data loss caused by accidental formatting. DO NOT REMOVE THE DRIVE WHILE FORMATTING!.
        /// </summary>
        internal static string FormatWarningP2Str {
            get {
                return ResourceManager.GetString("FormatWarningP2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to format drive .
        /// </summary>
        internal static string FormatWarningP3Str {
            get {
                return ResourceManager.GetString("FormatWarningP3Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string FormatWarningShortStr {
            get {
                return ResourceManager.GetString("FormatWarningShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Temporary Folder.
        /// </summary>
        internal static string InvalidTempFolderStr {
            get {
                return ResourceManager.GetString("InvalidTempFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This launches a wbfs game loader for .
        /// </summary>
        internal static string MetaXmlLongDescStr {
            get {
                return ResourceManager.GetString("MetaXmlLongDescStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on USB HDD.
        /// </summary>
        internal static string MetaXmlShortDescStr {
            get {
                return ResourceManager.GetString("MetaXmlShortDescStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry selected.
        /// </summary>
        internal static string MustSelectEntryToRemoveShortStr {
            get {
                return ResourceManager.GetString("MustSelectEntryToRemoveShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a single entry to remove..
        /// </summary>
        internal static string MustSelectEntryToRemoveStr {
            get {
                return ResourceManager.GetString("MustSelectEntryToRemoveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry selected.
        /// </summary>
        internal static string MustSelectEntryToRenameShortStr {
            get {
                return ResourceManager.GetString("MustSelectEntryToRenameShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a single entry to rename..
        /// </summary>
        internal static string MustSelectEntryToRenameStr {
            get {
                return ResourceManager.GetString("MustSelectEntryToRenameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder..
        /// </summary>
        internal static string MustSelectExistingFolderShortStr {
            get {
                return ResourceManager.GetString("MustSelectExistingFolderShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an existing folder..
        /// </summary>
        internal static string MustSelectExistingFolderStr {
            get {
                return ResourceManager.GetString("MustSelectExistingFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a valid temporary folder..
        /// </summary>
        internal static string MustSelectValidFolderText {
            get {
                return ResourceManager.GetString("MustSelectValidFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available..
        /// </summary>
        internal static string NewUpdateAvailableStr {
            get {
                return ResourceManager.GetString("NewUpdateAvailableStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives detected..
        /// </summary>
        internal static string NoDrivesDetectedShortStr {
            get {
                return ResourceManager.GetString("NoDrivesDetectedShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drive selected..
        /// </summary>
        internal static string NoDriveSelectedShortStr {
            get {
                return ResourceManager.GetString("NoDriveSelectedShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drive selected to add games to..
        /// </summary>
        internal static string NoDriveSelectedStr {
            get {
                return ResourceManager.GetString("NoDriveSelectedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No isos selected..
        /// </summary>
        internal static string NoIsoSelectedToAddShortStr {
            get {
                return ResourceManager.GetString("NoIsoSelectedToAddShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No isos selected to be added, use the browse button to add the isos to the Add list first..
        /// </summary>
        internal static string NoIsoSelectedToAddStr {
            get {
                return ResourceManager.GetString("NoIsoSelectedToAddStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailableShortStr {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableShortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently available..
        /// </summary>
        internal static string NoUpdatesAvailableStr {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Update Partition, Keep Rest.
        /// </summary>
        internal static string ParitionOptionRemoveUpdateStr {
            get {
                return ResourceManager.GetString("ParitionOptionRemoveUpdateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Partitions.
        /// </summary>
        internal static string PartitionOptionAllPartStr {
            get {
                return ResourceManager.GetString("PartitionOptionAllPartStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Game Partition.
        /// </summary>
        internal static string PartitonOptionOnlyGameStr {
            get {
                return ResourceManager.GetString("PartitonOptionOnlyGameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation will cancel when the current item has finished..
        /// </summary>
        internal static string ProgressCancellingText {
            get {
                return ResourceManager.GetString("ProgressCancellingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Files.
        /// </summary>
        internal static string ReadingFilesText {
            get {
                return ResourceManager.GetString("ReadingFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game list as:.
        /// </summary>
        internal static string SaveGameListAsStr {
            get {
                return ResourceManager.GetString("SaveGameListAsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the WAD file as....
        /// </summary>
        internal static string SaveWadFileAsStr {
            get {
                return ResourceManager.GetString("SaveWadFileAsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the base wad:.
        /// </summary>
        internal static string SelectBaseWadStr {
            get {
                return ResourceManager.GetString("SelectBaseWadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the common key file:.
        /// </summary>
        internal static string SelectCommonKeyFileStr {
            get {
                return ResourceManager.GetString("SelectCommonKeyFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Covers directory:.
        /// </summary>
        internal static string SelectCoversDirStr {
            get {
                return ResourceManager.GetString("SelectCoversDirStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory to extract the ISO files to:.
        /// </summary>
        internal static string SelectDirectoryToExtractToStr {
            get {
                return ResourceManager.GetString("SelectDirectoryToExtractToStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory to save to:.
        /// </summary>
        internal static string SelectDirForHBCStr {
            get {
                return ResourceManager.GetString("SelectDirForHBCStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image file to add:.
        /// </summary>
        internal static string SelectImageToAddStr {
            get {
                return ResourceManager.GetString("SelectImageToAddStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the USB loader DOL file:.
        /// </summary>
        internal static string SelectLoaderDolFileStr {
            get {
                return ResourceManager.GetString("SelectLoaderDolFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location and name to store the ISO image as:.
        /// </summary>
        internal static string SelectLocationExtractStr {
            get {
                return ResourceManager.GetString("SelectLocationExtractStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save the WAD files for the Channels in:.
        /// </summary>
        internal static string SelectWadOutputFolderStr {
            get {
                return ResourceManager.GetString("SelectWadOutputFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect any disk drives. Exiting WBFS Manager..
        /// </summary>
        internal static string UnableToDetectDrivesStr {
            get {
                return ResourceManager.GetString("UnableToDetectDrivesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected temporary folder does not have enough available free space, if you do not choose a different drive with at least 4.8 GB free you may experince problems extracting RAR archives..
        /// </summary>
        internal static string WarningNotEnoughSpaceTempStr {
            get {
                return ResourceManager.GetString("WarningNotEnoughSpaceTempStr", resourceCulture);
            }
        }
    }
}
